"""Fixed inputs with hand-checked expected outputs.

Every other test asserts a property. These assert the arithmetic, against
numbers worked out by hand and written down here with the working shown.
That makes them the only tests that catch a change which is internally
consistent and quietly wrong — a pricing multiplier edited, a category
moved, a discount applied twice. If one of these fails, either the change
was a mistake or the expected value below needs updating deliberately.

Nothing here uses recorded output. A golden file generated by the code it
tests only proves the code still agrees with itself.
"""

import json

from toka.adapters import parse_all
from toka.analyze import analyze
from toka.ingest import find_transcripts
from toka.pricing import PRICES

# claude-sonnet-4-5: $3.00 per Mtok input, $15.00 output.
# Multipliers: 5m write 1.25x, 1h write 2.0x, read 0.1x.
SONNET = PRICES["claude-sonnet-4-5"]
IN = SONNET.input_per_mtok / 1_000_000
OUT = SONNET.output_per_mtok / 1_000_000


def _write(tmp_path, name, records):
    path = tmp_path / name
    path.write_text(
        "\n".join(json.dumps(r) for r in records) + "\n", encoding="utf-8"
    )
    return path


def _anthropic(fresh, write_5m, write_1h, read, output, ts):
    return {
        "sessionId": "golden",
        "timestamp": ts,
        "message": {
            "model": "claude-sonnet-4-5",
            "usage": {
                "input_tokens": fresh,
                "cache_creation": {
                    "ephemeral_5m_input_tokens": write_5m,
                    "ephemeral_1h_input_tokens": write_1h,
                },
                "cache_creation_input_tokens": write_5m + write_1h,
                "cache_read_input_tokens": read,
                "output_tokens": output,
            },
        },
    }


def test_cost_split_is_exactly_what_the_rate_card_says(tmp_path):
    """Three requests, one session, every figure computed by hand.

        fresh input   1,000 +   500 +     0 =   1,500 tok @ 1.00x
        5m writes    10,000 +     0 + 2,000 =  12,000 tok @ 1.25x
        1h writes         0 + 4,000 +     0 =   4,000 tok @ 2.00x
        reads             0 + 8,000 + 9,000 =  17,000 tok @ 0.10x
        output          100 +   200 +   300 =     600 tok @ output rate
    """
    _write(
        tmp_path,
        "golden.jsonl",
        [
            _anthropic(1000, 10_000, 0, 0, 100, "2026-08-19T10:00:00Z"),
            _anthropic(500, 0, 4000, 8000, 200, "2026-08-19T10:00:30Z"),
            _anthropic(0, 2000, 0, 9000, 300, "2026-08-19T10:01:00Z"),
        ],
    )
    requests, used, skipped = parse_all(find_transcripts(tmp_path))
    assert used["claude-code"] == 1 and not skipped
    assert len(requests) == 3

    report = analyze(requests)
    assert len(report.sessions) == 1
    assert report.total_requests == 3

    assert report.cost_fresh_input == pytest_approx(1_500 * IN)
    assert report.cost_cache_write == pytest_approx(12_000 * IN * 1.25 + 4_000 * IN * 2.0)
    assert report.cost_cache_read == pytest_approx(17_000 * IN * 0.1)
    assert report.cost_output == pytest_approx(600 * OUT)

    # 1,500*0.000003 + (12,000*1.25 + 4,000*2)*0.000003
    #   + 17,000*0.1*0.000003 + 600*0.000015
    assert report.total_cost == pytest_approx(0.0045 + 0.069 + 0.0051 + 0.009)


def test_recoverable_is_the_two_mechanisms_and_nothing_else(tmp_path):
    """Cache miss covers fresh input after the first request only:
    500 tokens, charged at 1.0x where a hit would have cost 0.1x, so the
    avoidable part is 500 * rate * 0.9.

    Peak context is the largest single request: 500 + 4,000 + 8,000 =
    12,500. Total writes are 16,000. All requests are 30s apart, inside
    the 5-minute TTL, so nothing is discounted as expiry. Excess writes
    are therefore 16,000 - 12,500 - 0 = 3,500, charged at 1.25x where a
    read costs 0.1x.
    """
    _write(
        tmp_path,
        "golden.jsonl",
        [
            _anthropic(1000, 10_000, 0, 0, 100, "2026-08-19T10:00:00Z"),
            _anthropic(500, 0, 4000, 8000, 200, "2026-08-19T10:00:30Z"),
            _anthropic(0, 2000, 0, 9000, 300, "2026-08-19T10:01:00Z"),
        ],
    )
    report = analyze(parse_all(find_transcripts(tmp_path))[0])
    stats = next(iter(report.sessions.values()))

    assert stats.peak_context == 12_500
    assert stats.total_writes == 16_000
    assert stats.expiry_writes == 0
    assert stats.excess_writes == 3_500

    assert report.recoverable_miss == pytest_approx(500 * IN * 0.9)
    assert report.recoverable_excess_writes == pytest_approx(3_500 * IN * (1.25 - 0.1))
    assert report.recoverable == pytest_approx(
        report.recoverable_miss + report.recoverable_excess_writes
    )


def test_an_idle_gap_is_expiry_and_is_not_charged_as_waste(tmp_path):
    """The same three requests, but the last one comes an hour later.
    Its 2,000 writes follow a gap longer than the 5-minute TTL, so they
    are expiry — unavoidable re-warming — and drop out of excess writes:
    16,000 - 12,500 - 2,000 = 1,500.
    """
    _write(
        tmp_path,
        "golden.jsonl",
        [
            _anthropic(1000, 10_000, 0, 0, 100, "2026-08-19T10:00:00Z"),
            _anthropic(500, 0, 4000, 8000, 200, "2026-08-19T10:00:30Z"),
            _anthropic(0, 2000, 0, 9000, 300, "2026-08-19T11:30:00Z"),
        ],
    )
    report = analyze(parse_all(find_transcripts(tmp_path))[0])
    stats = next(iter(report.sessions.values()))

    assert stats.expiry_writes == 2_000
    assert stats.excess_writes == 1_500
    assert report.recoverable_excess_writes == pytest_approx(
        1_500 * IN * (1.25 - 0.1)
    )


def test_a_clean_session_reports_no_recoverable_spend(tmp_path):
    """Context grows, each token written once, nothing rewritten. The floor
    of the measurement has to be zero, or every user starts with a
    fictional bill to chase."""
    _write(
        tmp_path,
        "clean.jsonl",
        [
            _anthropic(1000, 5000, 0, 0, 50, "2026-08-19T10:00:00Z"),
            _anthropic(0, 0, 0, 5000, 50, "2026-08-19T10:00:10Z"),
            _anthropic(0, 0, 0, 5000, 50, "2026-08-19T10:00:20Z"),
        ],
    )
    report = analyze(parse_all(find_transcripts(tmp_path))[0])
    stats = next(iter(report.sessions.values()))

    assert stats.excess_writes == 0
    assert report.recoverable == 0.0
    assert report.recoverable_pct == 0.0


def test_an_unpriced_model_is_counted_in_tokens_and_not_in_dollars(tmp_path):
    """The rule that keeps every dollar figure defensible: no rate card,
    no price — not a price borrowed from a similar model."""
    _write(
        tmp_path,
        "unpriced.jsonl",
        [
            {
                "model": "some-model-nobody-publishes",
                "usage": {"prompt_tokens": 10_000, "completion_tokens": 500},
            }
        ],
    )
    report = analyze(parse_all(find_transcripts(tmp_path))[0])

    assert report.unpriced_requests == 1
    assert report.unpriced_tokens == 10_500
    assert report.total_cost == 0.0
    assert "some-model-nobody-publishes" in report.unpriced_models


def pytest_approx(value):
    import pytest

    return pytest.approx(value, rel=1e-9)
